title: Acid Masculinity
description: >-
  in the subject who desires, desire can be made to desire its own repression
baseurl: ""
url: "https://acidmasculinity.github.io"

theme: minima
plugins:
  - jekyll-feed

collections_dir: collections

collections:
  resource:
    output: false
  recovery:
    output: false
    sort_by: authors
  lore:
    output: false
    sort_by: authors
  aca_resource:
    output: false
    sort_by: authors
  digital:
    output: false
    sort_by: authors
  deviance:
    output: false
    sort_by: authors
  invisible:
    output: false
    sort_by: authors
  leisure:
    output: false
    sort_by: authors
  fascism:
    output: false
    sort_by: authors
  primary:
    output: false
    sort_by: authors

subjects:
  academic:
    name: Academic
  ability:
    name: Ability
  bodies:
    name: Bodies
  conspiracy:
    name: Conspiracy
  crime:
    name: Crime
  hooligans:
    name: Hooligans
  cults:
    name: Cults
  religion:
    name: Religion
  fandom:
    name: Fandom
  otaku:
    name: Otaku
  feminism:
    name: Feminism
  journalism:
    name: Journalism
  lore:
    name: Lore
  media_studies:
    name: Media
  manga:
    name: Manga
  hooligans:
    name: Hooligans
  internet:
    name: Internet
  masculinity:
    name: Masculinity
  psychology:
    name: Psychology
  queer:
    name: Queer
  trans:
    name: "Trans*"
  sociology:
    name: Sociology
  self_injury:
    name: Self-Injury
  theory:
    name: Theory
  sex:
    name: "Sex"
  urbanism:
    name: "Urbanism"
  philosophy:
    name: "Philosophy"
  literary:
    name: "Literary Theory"
  "other":
    name: "Other"
  propaganda:
    name: Propaganda

  media:
    name: "Media"
  original:
    name: "Original"
  former:
    name: Former
  former_book:
    name: Biographies
  self_help:
    name: Self-Help

defaults:
  - scope:
      type: "resource"
    values:
      authors: []

  - scope:
      type: "fascism"
    values:
      authors: []
  - scope:
      type: "fascism"
      path: "collections/_fascism/conspiracy"
    values:
      subject: conspiracy
  - scope:
      type: "fascism"
      path: "collections/_fascism/cults"
    values:
      subject: cults
  - scope:
      type: "fascism"
      path: "collections/_fascism/feminism"
    values:
      subject: feminism
  - scope:
      type: "fascism"
      path: "collections/_fascism/masculinity"
    values:
      subject: masculinity
  - scope:
      type: "fascism"
      path: "collections/_fascism/psychology"
    values:
      subject: psychology
  - scope:
      type: "fascism"
      path: "collections/_fascism/sociology"
    values:
      subject: sociology
  - scope:
      type: "fascism"
      path: "collections/_fascism/urban"
    values:
      subject: "urban"
  - scope:
      type: "fascism"
      path: "collections/_fascism/other"
    values:
      subject: "other"
  - scope:
      type: "fascism"
      path: "collections/_fascism/urbanism"
    values:
      subject: "urbanism"
  - scope:
      type: "fascism"
      path: "collections/_fascism/propaganda"
    values:
      subject: "propaganda"

  - scope:
      type: "digital"
    values:
      authors: []
  - scope:
      type: "digital"
      path: "collections/_digital/internet"
    values:
      subject: "internet"
  - scope:
      type: "digital"
      path: "collections/_digital/literary"
    values:
      subject: "literary"
  - scope:
      type: "digital"
      path: "collections/_digital/philosophy"
    values:
      subject: "philosophy"

  - scope:
      type: "deviance"
      path: "collections/_deviance/crime"
    values:
      subject: crime
  - scope:
      type: "deviance"
      path: "collections/_deviance/hooligans"
    values:
      subject: hooligans
  - scope:
      type: "deviance"
      path: "collections/_deviance/sex"
    values:
      subject: "sex"
  - scope:
      type: "deviance"
      path: "collections/_deviance/self_injury"
    values:
      subject: "self_injury"

  - scope:
      type: "invisible"
    values:
      authors: []
  - scope:
      type: "invisible"
      path: "collections/_invisible/ability"
    values:
      subject: ability
  - scope:
      type: "invisible"
      path: "collections/_invisible/queer"
    values:
      subject: queer
  - scope:
      type: "invisible"
      path: "collections/_invisible/trans"
    values:
      subject: trans

  - scope:
      type: "leisure"
    values:
      authors: []
  - scope:
      type: "leisure"
      path: "collections/_leisure/bodies"
    values:
      subject: bodies
  - scope:
      type: "leisure"
      path: "collections/_leisure/fandom"
    values:
      subject: fandom
  - scope:
      type: "leisure"
      path: "collections/_leisure/otaku"
    values:
      subject: otaku
  - scope:
      type: "leisure"
      path: "collections/_leisure/manga"
    values:
      subject: manga
  - scope:
      type: "leisure"
      path: "collections/_leisure/religion"
    values:
      subject: religion

  - scope:
      type: "recovery"
    values:
      authors: []
  - scope:
      type: "recovery"
      path: "collections/_recovery/fandom"
    values:
      subject: fandom
  - scope:
      type: "recovery"
      path: "collections/_recovery/former"
    values:
      subject: former
  - scope:
      type: "recovery"
      path: "collections/_recovery/ability"
    values:
      subject: ability
  - scope:
      type: "recovery"
      path: "collections/_recovery/former_book"
    values:
      subject: former_book
  - scope:
      type: "recovery"
      path: "collections/_recovery/self_help"
    values:
      subject: self_help
  - scope:
      type: "recovery"
      path: "collections/_recovery/media"
    values:
      subject: media
  - scope:
      type: "recovery"
      path: "collections/_recovery/masculinity"
    values:
      subject: masculinity
  - scope:
      type: "recovery"
      path: "collections/_recovery/queer"
    values:
      subject: queer
  - scope:
      type: "recovery"
      path: "collections/_recovery/trans"
    values:
      subject: trans
  - scope:
      type: "recovery"
      path: "collections/_recovery/lore"
    values:
      subject: lore
  - scope:
      type: "recovery"
      path: "collections/_recovery/urban"
    values:
      subject: urban
  - scope:
      type: "recovery"
      path: "collections/_recovery/cults"
    values:
      subject: cults

  - scope:
      type: "primary"
    values:
      authors: []
  - scope:
      type: "primary"
      path: "collections/_primary/media"
    values:
      subject: media
  - scope:
      type: "primary"
      path: "collections/_primary/original"
    values:
      subject: original
  - scope:
      type: "primary"
      path: "collections/_primary/other"
    values:
      subject: other

  - scope:
      type: "lore"
    values:
      authors: []
  - scope:
      type: "lore"
      path: "collections/_lore/lore"
    values:
      subject: lore

  - scope:
      type: "aca_resource"
    values:
      authors: []
  - scope:
      type: "aca_resource"
      path: "collections/_aca_resource/academic"
    values:
      subject: academic
  - scope:
      type: "aca_resource"
      path: "collections/_aca_resource/other"
    values:
      subject: other
