title: Acid Masculinity
description: >-
  in the subject who desires, desire can be made to desire its own repression
baseurl: ""
url: "https://acidmasculinity.github.io"

theme: minima
plugins:
  - jekyll-feed

collections_dir: collections

collections:
  resource:
    output: false
  recovery:
    output: false
    sort_by: authors
  media:
    output: false
    sort_by: authors
  lore:
    output: false
    sort_by: authors
  aca_resource:
    output: false
    sort_by: authors
  network:
    output: false
    sort_by: authors
  deviance:
    output: false
    sort_by: authors
  background:
    output: false
    sort_by: authors
  leisure:
    output: false
    sort_by: authors
  fascism:
    output: false
    sort_by: authors
  primary:
    output: false
    sort_by: authors

subjects:
  academic:
    name: Academic
  ability:
    name: Ability
  bodies:
    name: Bodies
  conspiracy:
    name: Conspiracy
  crime:
    name: Crime
  hooligans:
    name: Hooligans
  cults:
    name: Cults
  religion:
    name: Religion
  fandom:
    name: Fandom
  otaku:
    name: Otaku
  feminism:
    name: Feminism
  women:
    name: Women
  journalism:
    name: Journalism
  lore:
    name: Lore
  media_studies:
    name: Media
  manga:
    name: Manga
  hooligans:
    name: Hooligans
  network:
    name: "Network Culture"
  networked:
    name: "Networked Culture"
  economics:
    name: "Economics"
  masculinity:
    name: Masculinity
  psychology:
    name: Psychology
  queer:
    name: Queer
  men:
    name: Men
  trans:
    name: "Trans*"
  sociology:
    name: Sociology
  self_injury:
    name: Self-Injury
  theory:
    name: Theory
  sex:
    name: "Sex"
  urbanism:
    name: "Urbanism"
  philosophy:
    name: "Philosophy"
  literary:
    name: "Literary Theory"
  "other":
    name: "Other"
  propaganda:
    name: Propaganda
  anglo_america:
    name: "Anglo-America (Whiteness?)"

  media:
    name: "Media"
  media_popular:
    name: "Media Popular on the Far-Right"
  original:
    name: "Original"
  former:
    name: Former
  former_book:
    name: Biographies
  self_help:
    name: Self-Help
  gaming:
    name: Gaming
  whiteness:
    name: Whiteness

defaults:
  - scope:
      type: "resource"
    values:
      authors: []
      disabled: false

  - scope:
      type: "fascism"
    values:
      authors: []
      disabled: false
  - scope:
      type: "fascism"
      path: "collections/_fascism/conspiracy"
    values:
      subject: conspiracy
  - scope:
      type: "fascism"
      path: "collections/_fascism/cults"
    values:
      subject: cults
  - scope:
      type: "fascism"
      path: "collections/_fascism/masculinity"
    values:
      subject: masculinity
  - scope:
      type: "fascism"
      path: "collections/_fascism/psychology"
    values:
      subject: psychology
  - scope:
      type: "fascism"
      path: "collections/_fascism/other"
    values:
      subject: "other"
  - scope:
      type: "fascism"
      path: "collections/_fascism/gaming"
    values:
      subject: "gaming"
  - scope:
      type: "fascism"
      path: "collections/_fascism/whiteness"
    values:
      subject: "whiteness"
  - scope:
      type: "fascism"
      path: "collections/_fascism/queer"
    values:
      subject: "queer"
  - scope:
      type: "fascism"
      path: "collections/_fascism/otaku"
    values:
      subject: "otaku"
  - scope:
      type: "fascism"
      path: "collections/_fascism/religion"
    values:
      subject: religion
  - scope:
      type: "fascism"
      path: "collections/_fascism/women"
    values:
      subject: "women"
  - scope:
      type: "fascism"
      path: "collections/_fascism/men"
    values:
      subject: men
  - scope:
      type: "fascism"
      path: "collections/_fascism/networked"
    values:
      subject: networked
  - scope:
      type: "fascism"
      path: "collections/_fascism/lore"
    values:
      subject: lore


  - scope:
      type: "background"
    values:
      authors: []
      disabled: false
  - scope:
      type: "background"
      path: "collections/_background/ability"
    values:
      subject: ability
  - scope:
      type: "background"
      path: "collections/_background/bodies"
    values:
      subject: bodies
  - scope:
      type: "background"
      path: "collections/_background/network"
    values:
      subject: "network"
  - scope:
      type: "background"
      path: "collections/_background/literary"
    values:
      subject: "literary"
  - scope:
      type: "background"
      path: "collections/_background/anglo_america"
    values:
      subject: "anglo_america"
  - scope:
      type: "background"
      path: "collections/_background/other"
    values:
      subject: "other"

  - scope:
      type: "leisure"
    values:
      authors: []
      disabled: false
  - scope:
      type: "leisure"
      path: "collections/_leisure/fandom"
    values:
      subject: fandom
  - scope:
      type: "leisure"
      path: "collections/_leisure/otaku"
    values:
      subject: otaku
  - scope:
      type: "leisure"
      path: "collections/_leisure/manga"
    values:
      subject: manga
  - scope:
      type: "leisure"
      path: "collections/_leisure/gaming"
    values:
      subject: gaming
  - scope:
      type: "leisure"
      path: "collections/_leisure/religion"
    values:
      subject: religion
  - scope:
      type: "leisure"
      path: "collections/_leisure/sex"
    values:
      subject: "sex"

  - scope:
      type: "recovery"
    values:
      authors: []
      disabled: false
  - scope:
      type: "recovery"
      path: "collections/_recovery/fandom"
    values:
      subject: fandom
  - scope:
      type: "recovery"
      path: "collections/_recovery/former"
    values:
      subject: former
  - scope:
      type: "recovery"
      path: "collections/_recovery/ability"
    values:
      subject: ability
  - scope:
      type: "recovery"
      path: "collections/_recovery/self_help"
    values:
      subject: self_help
  - scope:
      type: "recovery"
      path: "collections/_recovery/masculinity"
    values:
      subject: masculinity
  - scope:
      type: "recovery"
      path: "collections/_recovery/queer"
    values:
      subject: queer
  - scope:
      type: "recovery"
      path: "collections/_recovery/trans"
    values:
      subject: trans
  - scope:
      type: "recovery"
      path: "collections/_recovery/lore"
    values:
      subject: lore
  - scope:
      type: "recovery"
      path: "collections/_recovery/urban"
    values:
      subject: urban
  - scope:
      type: "recovery"
      path: "collections/_recovery/cults"
    values:
      subject: cults

  - scope:
      type: "media"
    values:
      authors: []
      disabled: false
  - scope:
      type: "media"
      path: "collections/_media/media"
    values:
      subject: media
  - scope:
      type: "media"
      path: "collections/_media/former_book"
    values:
      subject: former_book

  - scope:
      type: "primary"
    values:
      authors: []
      disabled: false
  - scope:
      type: "primary"
      path: "collections/_primary/media_popular"
    values:
      subject: media
  - scope:
      type: "primary"
      path: "collections/_primary/original"
    values:
      subject: original
  - scope:
      type: "primary"
      path: "collections/_primary/propaganda"
    values:
      subject: propaganda

  - scope:
      type: "lore"
    values:
      authors: []
      disabled: false
  - scope:
      type: "lore"
      path: "collections/_lore/lore"
    values:
      subject: lore
  - scope:
      type: "lore"
      path: "collections/_lore/journalism"
    values:
      subject: journalism

  - scope:
      type: "aca_resource"
    values:
      authors: []
      disabled: false
  - scope:
      type: "aca_resource"
      path: "collections/_aca_resource/academic"
    values:
      subject: academic
  - scope:
      type: "aca_resource"
      path: "collections/_aca_resource/other"
    values:
      subject: other
