title: Acid Masculinity
description: >-
  in the subject who desires, desire can be made to desire its own repression
baseurl: ""
url: "https://acidmasculinity.github.io"

theme: minima
plugins:
  - jekyll-feed

collections:
  sources:
    output: false
    sort_by: authors

categories:
  ability:
    name: Ability
  crime:
    name: Crime
  feminism:
    name: Feminism
  former:
    name: former
  former_book:
    name: Former Book
  lore:
    name: Lore
  media:
    name: Media
  media_studies:
    name: Media Studies
  men:
    name: Men
  "psychology":
    name: Psychology
  "queer":
    name: Queer
  "self_help":
    name: Self-Help
  "sociology":
    name: Sociology
  "theory":
    name: Theory
  "porn":
    name: "Porn"
  "resource":
    name: "Resources"
  "far_right":
    name: "Far-right Canon"
    disabled: True
  "other":
    name: "other"

defaults:
  - scope:
      type: "sources"
    values:
      authors: []
  - scope:
      type: "sources"
      path: "_sources/ability"
    values:
      category: ability
  - scope:
      type: "sources"
      path: "_sources/crime"
    values:
      category: crime
  - scope:
      type: "sources"
      path: "_sources/feminism"
    values:
      category: feminism
  - scope:
      type: "sources"
      path: "_sources/former"
    values:
      category: former
  - scope:
      type: "sources"
      path: "_sources/former_book"
    values:
      category: former_book
  - scope:
      type: "sources"
      path: "_sources/lore"
    values:
      category: lore
  - scope:
      type: "sources"
      path: "_sources/media"
    values:
      category: media
  - scope:
      type: "sources"
      path: "_sources/media_studies"
    values:
      category: media_studies
  - scope:
      type: "sources"
      path: "_sources/men"
    values:
      category: men
  - scope:
      type: "sources"
      path: "_sources/psychology"
    values:
      category: psychology
  - scope:
      type: "sources"
      path: "_sources/queer"
    values:
      category: queer
  - scope:
      type: "sources"
      path: "_sources/self_help"
    values:
      category: self-help
  - scope:
      type: "sources"
      path: "_sources/sociology"
    values:
      category: sociology
  - scope:
      type: "sources"
      path: "_sources/theory"
    values:
      category: theory
  - scope:
      type: "sources"
      path: "_sources/porn"
    values:
      category: "porn"
  - scope:
      type: "sources"
      path: "_sources/resource"
    values:
      category: "resources"
  - scope:
      type: "sources"
      path: "_sources/far_right"
    values:
      category: "far_right"
  - scope:
      type: "sources"
      path: "_sources/other"
    values:
      category: "other"
