title: Acid Masculinity
description: >-
  in the subject who desires, desire can be made to desire its own repression
baseurl: ""
url: "https://acidmasculinity.github.io"

theme: minima
plugins:
  - jekyll-feed

collections:
  resource:
    output: false
  disengage:
    output: false
    sort_by: authors
  source:
    output: false
    sort_by: authors
  far_right:
    output: false
    sort_by: authors

subjects:
  ability:
    name: Ability
  bodies:
    name: Bodies
  conspiracy:
    name: Conspiracy
  crime:
    name: Crime
  cults:
    name: Cults
  feminism:
    name: Feminism
  lore:
    name: Lore
  media_studies:
    name: Media
  manga:
    name: Manga
  memes:
    name: Memes
  men:
    name: Men
  psychology:
    name: Psychology
  queer:
    name: Queer
  sociology:
    name: Sociology
  theory:
    name: Theory
  sex:
    name: "Sex"
  urban:
    name: "Urban"
  "other":
    name: "Other"

  media:
    name: "Media"
  former:
    name: Former
  former_book:
    name: Biographies
  self_help:
    name: Self-Help

defaults:
  - scope:
      type: "resource"
    values:
      authors: []

  - scope:
      type: "source"
    values:
      authors: []
  - scope:
      type: "source"
      path: "_source/ability"
    values:
      subject: ability
  - scope:
      type: "source"
      path: "_source/bodies"
    values:
      subject: bodies
  - scope:
      type: "source"
      path: "_source/crime"
    values:
      subject: crime
  - scope:
      type: "source"
      path: "_source/conspiracy"
    values:
      subject: conspiracy
  - scope:
      type: "source"
      path: "_source/cults"
    values:
      subject: cults
  - scope:
      type: "source"
      path: "_source/feminism"
    values:
      subject: feminism
  - scope:
      type: "source"
      path: "_source/lore"
    values:
      subject: lore
  - scope:
      type: "source"
      path: "_source/manga"
    values:
      subject: manga
  - scope:
      type: "source"
      path: "_source/media_studies"
    values:
      subject: media_studies
  - scope:
      type: "source"
      path: "_source/men"
    values:
      subject: men
  - scope:
      type: "source"
      path: "_source/psychology"
    values:
      subject: psychology
  - scope:
      type: "source"
      path: "_source/queer"
    values:
      subject: queer
  - scope:
      type: "source"
      path: "_source/sociology"
    values:
      subject: sociology
  - scope:
      type: "source"
      path: "_source/theory"
    values:
      subject: theory
  - scope:
      type: "source"
      path: "_source/sex"
    values:
      subject: "sex"
  - scope:
      type: "source"
      path: "_source/memes"
    values:
      subject: "memes"
  - scope:
      type: "source"
      path: "_source/urban"
    values:
      subject: "urban"
  - scope:
      type: "source"
      path: "_source/other"
    values:
      subject: "other"
  - scope:
      type: "source"
      path: "_source/far_right"
    values:
      subject: "far_right"

  - scope:
      type: "disengage"
    values:
      authors: []
  - scope:
      type: "disengage"
      path: "_disengage/former"
    values:
      subject: former
  - scope:
      type: "disengage"
      path: "_disengage/ability"
    values:
      subject: ability
  - scope:
      type: "disengage"
      path: "_disengage/former_book"
    values:
      subject: former_book
  - scope:
      type: "disengage"
      path: "_disengage/self_help"
    values:
      subject: self_help
  - scope:
      type: "disengage"
      path: "_disengage/media"
    values:
      subject: media
  - scope:
      type: "disengage"
      path: "_disengage/men"
    values:
      subject: men
  - scope:
      type: "disengage"
      path: "_disengage/queer"
    values:
      subject: queer

  - scope:
      type: "far_right"
    values:
      authors: []
  - scope:
      type: "far_right"
      path: "_far_right/media"
    values:
      subject: media
  - scope:
      type: "far_right"
      path: "_far_right/other"
    values:
      subject: other
