title: Acid Masculinity
description: >-
  in the subject who desires, desire can be made to desire its own repression
baseurl: ""
url: "https://acidmasculinity.github.io"

theme: minima
plugins:
  - jekyll-feed

collections:
  resource:
    output: false
  disengage:
    output: false
  source:
    output: false
    sort_by: authors

subjects:
  ability:
    name: Ability
  crime:
    name: Crime
  feminism:
    name: Feminism
  lore:
    name: Lore
  media:
    name: Media
  media_studies:
    name: Media Studies
  memes:
    name: Memes
  men:
    name: Men
  psychology:
    name: Psychology
  queer:
    name: Queer
  sociology:
    name: Sociology
  theory:
    name: Theory
  sex:
    name: "Sex"
  "other":
    name: "Other"
  media:
    name: "Artistic Works"
  "far_right":
    name: "Influential Among the Far-Right"

  former:
    name: Former Culture
  former_book:
    name: Former Biographies
  self_help:
    name: Self-Help

defaults:
  - scope:
      type: "source"
    values:
      authors: []
  - scope:
      type: "source"
      path: "_source/ability"
    values:
      subject: ability
  - scope:
      type: "source"
      path: "_source/crime"
    values:
      subject: crime
  - scope:
      type: "source"
      path: "_source/feminism"
    values:
      subject: feminism
  - scope:
      type: "source"
      path: "_source/lore"
    values:
      subject: lore
  - scope:
      type: "source"
      path: "_source/media_studies"
    values:
      subject: media_studies
  - scope:
      type: "source"
      path: "_source/men"
    values:
      subject: men
  - scope:
      type: "source"
      path: "_source/psychology"
    values:
      subject: psychology
  - scope:
      type: "source"
      path: "_source/queer"
    values:
      subject: queer
  - scope:
      type: "source"
      path: "_source/sociology"
    values:
      subject: sociology
  - scope:
      type: "source"
      path: "_source/theory"
    values:
      subject: theory
  - scope:
      type: "source"
      path: "_source/sex"
    values:
      subject: "sex"
  - scope:
      type: "source"
      path: "_source/memes"
    values:
      subject: "memes"
  - scope:
      type: "source"
      path: "_source/other"
    values:
      subject: "other"
  - scope:
      type: "source"
      path: "_source/media"
    values:
      subject: media
  - scope:
      type: "source"
      path: "_source/far_right"
    values:
      subject: "far_right"

  - scope:
      type: "resource"
    values:
      authors: []
  - scope:
      type: "disengage"
      path: "_disengage/former"
    values:
      subject: former
  - scope:
      type: "disengage"
      path: "_disengage/former_book"
    values:
      subject: former_book
  - scope:
      type: "disengage"
      path: "_disengage/self_help"
    values:
      subject: self_help
