title: Acid Masculinity
description: >-
  in the subject who desires, desire can be made to desire its own repression
baseurl: ""
url: "https://acidmasculinity.github.io"

theme: minima
plugins:
  - jekyll-feed

collections_dir: collections

collections:
  resource:
    output: false
  recovery:
    output: false
    sort_by: authors
  aca_resource:
    output: false
  source:
    output: false
    sort_by: authors
  primary:
    output: false
    sort_by: authors

subjects:
  ability:
    name: Ability
  bodies:
    name: Bodies
  conspiracy:
    name: Conspiracy
  crime:
    name: Crime
  religion:
    name: Religion
  feminism:
    name: Feminism
  lore:
    name: Lore
  media_studies:
    name: Media
  manga:
    name: Manga
  fandom:
    name: Fandom and Otaku
  internet:
    name: Internet
  masculinity:
    name: Masculinity
  psychology:
    name: Psychology
  queer:
    name: Queer
  trans:
    name: Trans
  sociology:
    name: Sociology
  self_injury:
    name: Self-Injury
  theory:
    name: Theory
  sex:
    name: "Sex"
  urban:
    name: "Urban"
  "other":
    name: "Other"

  media:
    name: "Media"
  original:
    name: "Original"
  former:
    name: Former
  former_book:
    name: Biographies
  self_help:
    name: Self-Help

defaults:
  - scope:
      type: "resource"
    values:
      authors: []

  - scope:
      type: "source"
    values:
      authors: []
  - scope:
      type: "source"
      path: "collections/_source/ability"
    values:
      subject: ability
  - scope:
      type: "source"
      path: "collections/_source/bodies"
    values:
      subject: bodies
  - scope:
      type: "source"
      path: "collections/_source/crime"
    values:
      subject: crime
  - scope:
      type: "source"
      path: "collections/_source/conspiracy"
    values:
      subject: conspiracy
  - scope:
      type: "source"
      path: "collections/_source/religion"
    values:
      subject: religion
  - scope:
      type: "source"
      path: "collections/_source/feminism"
    values:
      subject: feminism
  - scope:
      type: "source"
      path: "collections/_source/lore"
    values:
      subject: lore
  - scope:
      type: "source"
      path: "collections/_source/manga"
    values:
      subject: manga
  - scope:
      type: "source"
      path: "collections/_source/fandom"
    values:
      subject: fandom
  - scope:
      type: "source"
      path: "collections/_source/media_studies"
    values:
      subject: media_studies
  - scope:
      type: "source"
      path: "collections/_source/masculinity"
    values:
      subject: masculinity
  - scope:
      type: "source"
      path: "collections/_source/psychology"
    values:
      subject: psychology
  - scope:
      type: "source"
      path: "collections/_source/queer"
    values:
      subject: queer
  - scope:
      type: "source"
      path: "collections/_source/trans"
    values:
      subject: trans
  - scope:
      type: "source"
      path: "collections/_source/sociology"
    values:
      subject: sociology
  - scope:
      type: "source"
      path: "collections/_source/theory"
    values:
      subject: theory
  - scope:
      type: "source"
      path: "collections/_source/sex"
    values:
      subject: "sex"
  - scope:
      type: "source"
      path: "collections/_source/internet"
    values:
      subject: "internet"
  - scope:
      type: "source"
      path: "collections/_source/self_injury"
    values:
      subject: "self_injury"
  - scope:
      type: "source"
      path: "collections/_source/urban"
    values:
      subject: "urban"
  - scope:
      type: "source"
      path: "collections/_source/other"
    values:
      subject: "other"
  - scope:
      type: "source"
      path: "collections/_source/primary"
    values:
      subject: "primary"

  - scope:
      type: "recovery"
    values:
      authors: []
  - scope:
      type: "recovery"
      path: "collections/_recovery/fandom"
    values:
      subject: fandom
  - scope:
      type: "recovery"
      path: "collections/_recovery/former"
    values:
      subject: former
  - scope:
      type: "recovery"
      path: "collections/_recovery/ability"
    values:
      subject: ability
  - scope:
      type: "recovery"
      path: "collections/_recovery/former_book"
    values:
      subject: former_book
  - scope:
      type: "recovery"
      path: "collections/_recovery/self_help"
    values:
      subject: self_help
  - scope:
      type: "recovery"
      path: "collections/_recovery/media"
    values:
      subject: media
  - scope:
      type: "recovery"
      path: "collections/_recovery/masculinity"
    values:
      subject: masculinity
  - scope:
      type: "recovery"
      path: "collections/_recovery/queer"
    values:
      subject: queer
  - scope:
      type: "recovery"
      path: "collections/_recovery/trans"
    values:
      subject: trans
  - scope:
      type: "recovery"
      path: "collections/_recovery/lore"
    values:
      subject: lore
  - scope:
      type: "recovery"
      path: "collections/_recovery/urban"
    values:
      subject: urban

  - scope:
      type: "primary"
    values:
      authors: []
  - scope:
      type: "primary"
      path: "collections/_primary/media"
    values:
      subject: media
  - scope:
      type: "primary"
      path: "collections/_primary/original"
    values:
      subject: original
  - scope:
      type: "primary"
      path: "collections/_primary/other"
    values:
      subject: other
