title: Acid Masculinity
description: >-
  in the subject who desires, desire can be made to desire its own repression
baseurl: ""
url: "https://acidmasculinity.github.io"

theme: minima
plugins:
  - jekyll-feed

collections:
  sources:
    output: false
    sort_by: authors

defaults:
  - scope:
      type: "sources"
      path: "_sources/ability"
    values:
      category: Ability
  - scope:
      type: "sources"
      path: "_sources/crime"
    values:
      category: Crime
  - scope:
      type: "sources"
      path: "_sources/feminism"
    values:
      category: Feminism
  - scope:
      type: "sources"
      path: "_sources/former"
    values:
      category: Former
  - scope:
      type: "sources"
      path: "_sources/former_book"
    values:
      category: "Former Book"
  - scope:
      type: "sources"
      path: "_sources/lore"
    values:
      category: Lore
  - scope:
      type: "sources"
      path: "_sources/media"
    values:
      category: Media
  - scope:
      type: "sources"
      path: "_sources/media_studies"
    values:
      category: Media Studies
  - scope:
      type: "sources"
      path: "_sources/men"
    values:
      category: Men
  - scope:
      type: "sources"
      path: "_sources/psychology"
    values:
      category: Psychology
  - scope:
      type: "sources"
      path: "_sources/queer"
    values:
      category: Queer
  - scope:
      type: "sources"
      path: "_sources/self_help"
    values:
      category: Self-Help
  - scope:
      type: "sources"
      path: "_sources/sociology"
    values:
      category: Sociology
  - scope:
      type: "sources"
      path: "_sources/theory"
    values:
      category: Theory
  - scope:
      type: "sources"
      path: "_sources/porn"
    values:
      category: "Porn"
  - scope:
      type: "sources"
      path: "_sources/other"
    values:
      category: "Other"
