- name: Feminism
  sources:
    - authors: "Simone de Beauvoir"
      title: "The Second Sex: Facts and Myths"
    - authors: Andrea Dworkin
      title: "Right-Wing Women: The Politics of Domesticated Females"
    - authors: Cameron Awkward-Rich
      title: "Trans, Feminism: Or, Reading like a Depressed Transsexual"
    - authors: bell hooks
      title: "Sisterhood: Political Solidarity between Women"

- name: Former Biographies
  sources:
    - authors: Eli Saslow
      title: "Rising Out of Hatred: The Awakening of a Former White Nationalist"
    - authors: Tony McAleer
      title: "The Cure for Hate: A Former White Supremacist’s Journey from Violent Extremism to Radical Compassion"
    - authors: Christian Picciolini
      title: "White American Youth: My Descent into America's Most Violent Hate Movement"
    - authors: "Ingo Hasselbach, Tom Reiss"
      title: "Führer Ex: Memoirs of a Former Neo-Nazi"
    - authors: "Frank Meeink, Jody M. Roy"
      title: "Autobiography of a Recovering Skinhead: The Frank Meeink Story as Told to Jody M. Roy, Ph. D."

- name: Porn Studies
  sources:
    - authors: Laura Williams
      title: "Hard Core: Power, Pleasure and the "Frenzy of the Visible""
    - authors: Ariane Cruz
      title: "The Color of Kink: Black Women, BDSM, and Pornography"
    - authors: Kimi Rito
      title: "The History of Hentai Manga"

- name: Police and Crime
  sources:
    - authors: Sayak Valencia
      title: Gore Capitalism
    - authors: Kristian Williams
      title: Our Enemies in Blue: Police and Power in America

- name: Sociology
  sources:
    - authors: "Kathleen M. Blee"
      title: "Inside Organized Racism: Women in the Hate Movement"
    - authors: "Michael Kimmel"
      title: Healing from Hate

- name: Theory
  sources:
    - authors: Jean-Paul Sartre
      title: Anti-Semite and Jew
    - authors: Wilhelm Reich
      title: The Mass Psychology of Fascism

- name: Ability
  sources:
    - authors: Hilla Kauppinen
      title: "Always Disabled: Navigating Grief over a Lost Childhood"
      site: Cripple Media
      URL: "https://cripplemedia.com/me-autism-and-the-efforts-to-cure-us/"
    - authors: Devon Price
      title: "Unmasking Autism: Discovering the New Faces of Neurodiversity"

- name: Other
  sources:
    - authors: Devon Price
      title: Laziness Does Not Exist
    - authors: DarkWebInsider
      title: >-
       An Interview With "Incel Whisperer" Mike Crumplar
      site: Countere Magazine
      URL: "https://www.countere.com/home/mikecrumplarincels"
    - authors: "Christopher Douglas and Matthew Mullins"
      title: "W(h)ither the Christian Right?"
      site: Post45
      URL: "https://post45.org/sections/contemporaries-essays/whither-the-christian-right/"

