- name: Theory
  sources:
    - authors: Jean-Paul Sartre
      title: Anti-Semite and Jew
    - authors: Wilhelm Reich
      title: The Mass Psychology of Fascism

- name: Ability
  sources:
    - authors: Hilla Kauppinen
      title: "Always Disabled: Navigating Grief over a Lost Childhood"
      site: Cripple Media
      URL: "https://cripplemedia.com/me-autism-and-the-efforts-to-cure-us/"
    - authors: Devon Price
      title: "Unmasking Autism: Discovering the New Faces of Neurodiversity"

- name: Other
  sources:
    - authors: Devon Price
      title: Laziness Does Not Exist
    - authors: DarkWebInsider
      title: >-
       An Interview With "Incel Whisperer" Mike Crumplar
      site: Countere Magazine
      URL: "https://www.countere.com/home/mikecrumplarincels"
    - authors: "Christopher Douglas and Matthew Mullins"
      title: "W(h)ither the Christian Right?"
      site: Post45
      URL: "https://post45.org/sections/contemporaries-essays/whither-the-christian-right/"

