- authors: Devon Price
  title: Laziness Does Not Exist
- authors: DarkWebInsider
  title: "An Interview With "Incel Whisperer" Mike Crumplar"
  site: Countere Magazine
  URL: https://www.countere.com/home/mikecrumplarincels
- authors: "Christopher Douglas and Matthew Mullins"
  title: "W(h)ither the Christian Right?"
  site: Post45
  URL: https://post45.org/sections/contemporaries-essays/whither-the-christian-right/

