type Bib implements Node @childOf(types: ["File"]) {
  id: ID!
  section: String!
  subsection: String!

  title: String!
  content: String!
  authors: [String!]!

  article: String
  link: String

  year: Int

  disabled: Boolean
}
