type Bib implements Node @childOf(types: ["MarkdownRemark"]) {
  id: ID!
  section: String!
  subsection: String!

  disabled: Boolean!

  title: String!
  authors: [String!]!

  article: String
  site: String
  link: String
  year: Int
}
